services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\TranslationReport\:
    resource: '../Classes/*'

  GeorgRinger\TranslationReport\Controller\TranslationReportController:
    tags: ['backend.controller']
